name: Run API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure these are present even if not in requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage (force reports)
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: |
          # Show where we are
          echo "PWD is: $(pwd)"
          ls -la
          #override addopts to avoid any conflicts with pytest.ini
          #generate HTML + XML explicitly to guarantee htmlcov/ exists
          pytest -o addopts="" --cov=. --cov-fail-under=85 \
                 --cov-report=term-missing \
                 --cov-report=xml:coverage.xml \
                 --cov-report=html:htmlcov
          echo "Listing htmlcov after pytest:"
          ls -la htmlcov || true

      # upload even if tests fail so you can see the report/logs
      - name: Upload HTML coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: ${{ github.workspace }}/htmlcov
          if-no-files-found: warn
          retention-days: 7
